[package]
name = "bahilizator"
version = "2.0.0"
edition = "2021"

[dependencies]
embassy-stm32 = { version = "0.6", features = ["stm32f103c8", "time-driver-tim2", "unstable-pac"] }
embassy-executor = { version = "0.7", features = ["arch-cortex-m", "executor-thread"] }
embassy-time = "0.4"
embassy-sync = "0.6"
embassy-futures = "0.1"

cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
panic-probe = "1.0"
defmt = "1.0"
defmt-rtt = "1.0"

heapless = "0.8"
embedded-hal-async = "1.0"
embedded-io-async = "0.6"
bitflags = "2.6"
static_cell = "2.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true