[package]
name = "bahilizator"
version = "2.0.0"
edition = "2021"

[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", features = ["stm32f103c8", "time-driver-tim2", "defmt"] }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", features = ["executor-thread", "defmt", "platform-cortex-m"] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git" }

cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-probe = { version = "0.3", features = ["print-defmt"] }
defmt = "0.3"
defmt-rtt = "0.4"
critical-section = "1.1"

heapless = "0.9"
one-wire-bus = "0.1"
embedded-hal = { version = "0.2", package = "embedded-hal", features = ["unproven"] }
embedded-hal-async = "1.0"
embedded-io-async = "0.7"
bitflags = "2.6"
static_cell = "2.1"

embassy-net-ppp = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-net = { git = "https://github.com/embassy-rs/embassy.git", features = ["defmt", "medium-ip", "proto-ipv4", "dns", "tcp", "udp", "dhcpv4"] }
rust-mqtt = { version = "0.5.1", default-features = false, features = ["v5", "defmt"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true