[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "linker=xtensa-esp32-elf-gcc",
    "-C", "link-arg=-Wl,-Tlinkall.x",
    "-C", "link-arg=-nostartfiles",
]

[build]
target = "xtensa-esp32-none-elf"

[env]
DEFMT_LOG = "info"